// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVSF-FD2TL4MSIigk4NNQRNCZfL20gCg',
    appId: '1:505532381205:web:9fd841de7bb57e9a20361c',
    messagingSenderId: '505532381205',
    projectId: 'asistenciaupeu-f49db',
    authDomain: 'asistenciaupeu-f49db.firebaseapp.com',
    storageBucket: 'asistenciaupeu-f49db.firebasestorage.app',
    measurementId: 'G-QVH98902E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrlBMmb9oDC7wVbM35UY4aEYOjrWM-KV8',
    appId: '1:505532381205:android:6c9247103c5acdb420361c',
    messagingSenderId: '505532381205',
    projectId: 'asistenciaupeu-f49db',
    storageBucket: 'asistenciaupeu-f49db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_d224nBFIhoCznWiz9D83aHztFmsq_g',
    appId: '1:505532381205:ios:f7f6f0d1205308ba20361c',
    messagingSenderId: '505532381205',
    projectId: 'asistenciaupeu-f49db',
    storageBucket: 'asistenciaupeu-f49db.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ_d224nBFIhoCznWiz9D83aHztFmsq_g',
    appId: '1:505532381205:ios:f7f6f0d1205308ba20361c',
    messagingSenderId: '505532381205',
    projectId: 'asistenciaupeu-f49db',
    storageBucket: 'asistenciaupeu-f49db.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGVSF-FD2TL4MSIigk4NNQRNCZfL20gCg',
    appId: '1:505532381205:web:1e8ee0cfb308f47720361c',
    messagingSenderId: '505532381205',
    projectId: 'asistenciaupeu-f49db',
    authDomain: 'asistenciaupeu-f49db.firebaseapp.com',
    storageBucket: 'asistenciaupeu-f49db.firebasestorage.app',
    measurementId: 'G-SM4X8RGELP',
  );
}
